version: '3'

services:
  jupyter-server:
    build:
      context: ./jupyter/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/usr/src/app
      - ./data:/usr/src/data
    command: ["start-notebook.sh", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb  # Use the service name as the host

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # Expose the MongoDB port to the host
    volumes:
      - ./mongodb-data:/usr/src/mongodb-data