version: '3'

services:
  jupyter-server:
    image: jupyter-server
    build:
      context: ./jupyter/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/usr/src/app
      - ./data:/usr/src/data
    command: ["start-notebook.sh", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]